export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DISPLAY_POPUP = 'SHOW_POPUP';
export const CLEAR_POPUP = 'CLEAR_POPUP';